### PR TITLE
Fix asyncio timeout error at startup

### LINKED ISSUE #198: asyncio.TimeoutError crash at core-engine backend startup
Hi,

I'm following the very [first tutorial](https://docs.swiss-ai-center.ch/tutorials/start-the-core-engine/) to start the core engine locally.

After `docker compose build` and `docker compose up`, the application seems to crash at startup:

```
$ docker compose up
...
backend  | Requirement already satisfied: pydantic-core==2.14.6 in ./.venv/lib/python3.10/site-packages (from pydantic==2.5.3->-r requirements-all.txt (line 39)) (2.14.6)
backend  |
backend  | [notice] A new release of pip is available: 23.0.1 -> 24.0
backend  | [notice] To update, run: pip install --upgrade pip
backend  | INFO:     Will watch for changes in these directories: ['/workspaces/core-engine-backend/src']
backend  | INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
backend  | INFO:     Started reloader process [1] using StatReload
backend  | INFO:     Started server process [53]
backend  | INFO:     Waiting for application startup.
backend  | INFO:     [2024-03-05 13:28:31,408]  [pipelines.service]:    Checking storage availability...
backend  | ERROR:    [2024-03-05 13:33:20,489]  Traceback (most recent call last):
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
backend  |     return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
backend  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
backend  |     sock = await self._connect_sock(
backend  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
backend  |     await self.sock_connect(sock, address)
backend  |   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
backend  |     return await fut
backend  | asyncio.exceptions.CancelledError
backend  |
backend  | During handling of the above exception, another exception occurred:
backend  |
backend  | Traceback (most recent call last):
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
backend  |     conn = await self._connector.connect(
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
backend  |     proto = await self._create_connection(req, traces, timeout)
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
backend  |     _, proto = await self._create_direct_connection(req, traces, timeout)
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
backend  |     transp, proto = await self._wrap_create_connection(
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 979, in _wrap_create_connection
backend  |     async with ceil_timeout(timeout.sock_connect):
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
backend  |     self._do_exit(exc_type)
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
backend  |     raise asyncio.TimeoutError
backend  | asyncio.exceptions.TimeoutError
backend  |
backend  | The above exception was the direct cause of the following exception:
backend  |
backend  | Traceback (most recent call last):
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/httpsession.py", line 208, in send
backend  |     response = await self._session.request(
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 540, in _request
backend  |     raise ServerTimeoutError(
backend  | aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host http://host.docker.internal:9000/engine/0000-0000-0000-0000
backend  |
backend  | During handling of the above exception, another exception occurred:
backend  |
backend  | Traceback (most recent call last):
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/starlette/routing.py", line 692, in lifespan
backend  |     async with self.lifespan_context(app) as maybe_state:
backend  |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
backend  |     return await anext(self.gen)
backend  |   File "/workspaces/core-engine-backend/src/./main.py", line 96, in lifespan
backend  |     await storage_service.check_storage_availability()
backend  |   File "/workspaces/core-engine-backend/src/./storage/service.py", line 40, in check_storage_availability
backend  |     await client.get_object(Bucket=self.s3_bucket, Key=self.FAKE_KEY_ID)
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/client.py", line 341, in _make_api_call
backend  |     http, parsed_response = await self._make_request(
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/client.py", line 366, in _make_request
backend  |     return await self._endpoint.make_request(
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/endpoint.py", line 100, in _send_request
backend  |     while await self._needs_retry(
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/endpoint.py", line 262, in _needs_retry
backend  |     responses = await self._event_emitter.emit(
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/hooks.py", line 66, in _emit
backend  |     response = await resolve_awaitable(handler(**kwargs))
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/_helpers.py", line 15, in resolve_awaitable
backend  |     return await obj
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/retryhandler.py", line 107, in _call
backend  |     if await resolve_awaitable(self._checker(**checker_kwargs)):
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/_helpers.py", line 15, in resolve_awaitable
backend  |     return await obj
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/retryhandler.py", line 126, in _call
backend  |     should_retry = await self._should_retry(
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/retryhandler.py", line 165, in _should_retry
backend  |     return await resolve_awaitable(
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/_helpers.py", line 15, in resolve_awaitable
backend  |     return await obj
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/retryhandler.py", line 174, in _call
backend  |     checker(attempt_number, response, caught_exception)
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 247, in __call__
backend  |     return self._check_caught_exception(
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
backend  |     raise caught_exception
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/endpoint.py", line 181, in _do_get_response
backend  |     http_response = await self._send(request)
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/endpoint.py", line 285, in _send
backend  |     return await self.http_session.send(request)
backend  |   File "/workspaces/core-engine-backend/.venv/lib/python3.10/site-packages/aiobotocore/httpsession.py", line 245, in send
backend  |     raise ConnectTimeoutError(endpoint_url=request.url, error=e)
backend  | botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://host.docker.internal:9000/engine/0000-0000-0000-0000"
backend  |
backend  | ERROR:    [2024-03-05 13:33:20,489]  Application startup failed. Exiting.
db       | 2024-03-05 13:33:25.826 UTC [22] LOG:  checkpoint starting: time
db       | 2024-03-05 13:33:25.848 UTC [22] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.002 s, total=0.023 s; sync files=2, longest=0.002 s, average=0.001 s; distance=0 kB, estimate=0 kB
```

Trying to reach `127.0.0.1:8080`, `127.0.0.1:8080/docs` or `localhost:8080/docs` does not yield any result. I can however access the local minio server on `localhost:9001`.

This happened on both WSL2 running Arch, and a clean VirtualBox VM running Ubuntu 22.04.
Using latest core-engine commit (6eb1757) on main branch.

Any suggestion welcome.

### PR DESCRIPTION
**Pull request by rmarquis**
Fix asyncio timeout error at startup on Linux, by @ludelafo. The fixes has been validated on macos by @andrptrc.

Fixes #198.

### CODE REVIEW

**Review by andrptrc — CHANGES_REQUESTED** [review]
To be compliant with the hosts in every files, can you change the DATABASE_URL for PostgreSQL in the `.env` file to use host.docker.internal as well ?

**Comment by ludelafo** [comment]
I tinkered around to find another solution but the current solution seems to be the easier to implement.

I did try to set the Docker Compose as follow but it doesn't work:

```diff
diff --git a/backend/docker-compose.yml b/backend/docker-compose.yml
index 37f757e..b6975c7 100644
--- a/backend/docker-compose.yml
+++ b/backend/docker-compose.yml
@@ -27,7 +27,7 @@ services:
       - mc
     environment:
       - HOST=http://host.docker.internal:8080/
-      - S3_HOST=http://host.docker.internal:9000/
+      - S3_HOST=http://host-gateway:9000/
     ports:
       - 8080:8080
     working_dir: /workspaces/core-engine-backend
```

Another solution would be to add a network to each service but it is many changes that the current solution seems to be enough for this problem.

**Comment by andrptrc** [comment]
> I tinkered around to find another solution but the current solution seems to be the easier to implement.
> 
> I did try to set the Docker Compose as follow but it doesn't work:
> 
> ```diff
> diff --git a/backend/docker-compose.yml b/backend/docker-compose.yml
> index 37f757e..b6975c7 100644
> --- a/backend/docker-compose.yml
> +++ b/backend/docker-compose.yml
> @@ -27,7 +27,7 @@ services:
>        - mc
>      environment:
>        - HOST=http://host.docker.internal:8080/
> -      - S3_HOST=http://host.docker.internal:9000/
> +      - S3_HOST=http://host-gateway:9000/
>      ports:
>        - 8080:8080
>      working_dir: /workspaces/core-engine-backend
> ```
> 
> Another solution would be to add a network to each service but it is many changes that the current solution seems to be enough for this problem.

So the what final state do we keep ? The one with `extra_hosts` and `host.docker.internal`?

**Comment by rmarquis** [comment]
As a sidenote and reminder: whichever is the modification retained, it should also be applied to each service to allow them to successfully register to the core-engine on Linux.

**Pull request merged**
